<?php

use AhmedArafat\AllInOne\Commands\DatabaseInitialSeedersCommand;
use AhmedArafat\AllInOne\Commands\GitCommand;
use AhmedArafat\AllInOne\Middleware\JwtMiddleware;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;

class AllInOneServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $this->commands([
            GitCommand::class,
            DatabaseInitialSeedersCommand::class,
        ]);
        Route::aliasMiddleware(
            'jwt',
            JwtMiddleware::class
        );
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
